version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#  application:
#    build: application/.
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      - VERSION=1.0.0
#  nginx:
#    build: nginx/Dockerfile
#    depends_on:
#      - application
#    ports:
#      - "8080:80"
#    volumes:
#      - ./.docker/nginx:/u